# Generated by Django 6.0.5 on 2026-05-23 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.CharField(help_text='Ví dụ: 0001, 0002', max_length=10, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['store_number'],
            },
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='⚠️', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('default_pic', models.ForeignKey(blank=True, help_text='Người Core Team xử lý lỗi này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('bod', 'BOD'), ('core_team', 'Core Team'), ('senior_staff', 'Senior Staff'), ('staff', 'Staff')], default='staff', max_length=15)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=30000, help_text='Lương theo giờ (VND)', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_store', models.ForeignKey(blank=True, help_text='Tiệm được gán (chỉ dùng cho Senior Staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('washer', 'Máy giặt'), ('dryer', 'Máy sấy')], max_length=10)),
                ('machine_no', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.store')),
            ],
            options={
                'ordering': ['machine_type', 'machine_no'],
                'unique_together': {('store', 'machine_type', 'machine_no')},
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('resolved', 'Hoàn thành')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('error_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.errortype')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_incidents', to=settings.AUTH_USER_MODEL)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_role', models.CharField(choices=[('bod', 'BOD'), ('core_team', 'Core Team'), ('senior_staff', 'Senior Staff'), ('staff', 'Staff')], default='staff', max_length=15)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
