# Generated by Django 6.0.5 on 2026-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Bắt buộc đổi mật khẩu lần đăng nhập đầu'),
        ),
    ]
